name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: analystsayan
          outputs:  |
            dist/github-contribution-grid-snake-dark.svg
            dist/github-contribution-grid-snake-dark.gif
      - name: Push the changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate GitHub contribution snake"
